export default {
  id: "inferx",
  priority: 45,
  hasFree: true,
  alias: "ix",
  uiAlias: "ix",
  display: {
    name: "InferX",
    icon: "memory",
    color: "#7C3AED",
    textIcon: "IX",
    website: "https://model.inferx.net/catalog/endpoints",
    notice: {
      text: "Modelos self-hosted OpenAI-compatíveis. Obtenha sua API key no portal InferX.",
      apiKeyUrl: "https://model.inferx.net/catalog/endpoints",
    },
  },
  category: "apikey",
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://model.inferx.net/endpoints/v1/chat/completions",
    thinkingFormat: "openai",
  },
  models: [
    { id: "Devstral-2-123B-Instruct-2512-int4-AutoRound", name: "Devstral 2 123B Instruct" },
    { id: "Qwen3-Coder-Next-FP8", name: "Qwen3 Coder Next" },
    { id: "Qwen3.6-35B-A3B-FP8", name: "Qwen3.6 35B A3B" },
    { id: "Qwen3.8-27B-FP8", name: "Qwen3.8 27B" },
    { id: "qwen38-flash-next", name: "Qwen3.8 Flash Next" },
    { id: "gemma-4-31B-it-fp8", name: "Gemma 4 31B Instruct" },
    { id: "gpt-oss-20b", name: "GPT OSS 20B" },
    { id: "deepseek-v4-flash-0731", name: "DeepSeek V4 Flash" },
    { id: "deepseek-v4-flash-vision-exp", name: "DeepSeek V4 Flash Vision" },
    { id: "glm-5.3-flash", name: "GLM 5.3 Flash" },
    { id: "Agents-A1", name: "Agents A1" },
  ],
  serviceKinds: ["llm"],
};
