export default {
  id: "orcarouter",
  priority: 40,
  hasFree: true,
  alias: "orca",
  uiAlias: "orca",
  display: {
    name: "OrcaRouter",
    icon: "router",
    color: "#0EA5E9",
    textIcon: "ORC",
    website: "https://www.orcarouter.ai",
    notice: {
      text: "200+ modelos através de uma única API. Modelos gratuitos (deepseek-v4-flash-free, glm-5.3-flash-free, hy3-free, orcarouter/free) precisam de conta grátis + chave API.",
      apiKeyUrl: "https://www.orcarouter.ai/console",
    },
  },
  category: "freeTier",
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://api.orcarouter.ai/v1/chat/completions",
    thinkingFormat: "openai",
  },
  models: [
    { id: "orcarouter/free", name: "OrcaRouter Free (auto)", isFree: true },
    { id: "deepseek/deepseek-v4-flash-free", name: "DeepSeek V4 Flash (Free)", isFree: true },
    { id: "z-ai/glm-5.3-flash-free", name: "Z.ai GLM 5.3 Flash (Free)", isFree: true },
    { id: "tencent/hy3-free", name: "Tencent HY3 (Free)", isFree: true },
    { id: "orcarouter/auto", name: "OrcaRouter Auto" },
    { id: "orcarouter/fusion", name: "OrcaRouter Fusion" },
    { id: "orcarouter/fusion-flash", name: "OrcaRouter Fusion Flash" },
    { id: "orcarouter/fusion-mini", name: "OrcaRouter Fusion Mini" },
    { id: "deepseek/deepseek-chat", name: "DeepSeek V3" },
    { id: "deepseek/deepseek-reasoner", name: "DeepSeek R1" },
    { id: "deepseek/deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "deepseek/deepseek-v4-flash-0731", name: "DeepSeek V4 Flash 0731" },
    { id: "qwen/qwen3-max", name: "Qwen 3 Max" },
    { id: "qwen/qwen3.8-27b", name: "Qwen 3.8 27B" },
    { id: "qwen/qwen3.8-flash", name: "Qwen 3.8 Flash" },
    { id: "qwen/qwen3.7-flash", name: "Qwen 3.7 Flash" },
    { id: "z-ai/glm-5", name: "Z.ai GLM 5" },
    { id: "z-ai/glm-4.7", name: "Z.ai GLM 4.7" },
    { id: "tencent/hy3", name: "Tencent HY3" },
    { id: "anthropic/claude-opus-4.6", name: "Claude Opus 4.6" },
    { id: "anthropic/claude-haiku-4.5", name: "Claude Haiku 4.5" },
    { id: "openai/gpt-4o", name: "GPT-4o" },
    { id: "openai/gpt-4o-mini", name: "GPT-4o Mini" },
    { id: "google/gemini-2.5-flash", name: "Gemini 2.5 Flash" },
    { id: "google/gemini-2.5-pro", name: "Gemini 2.5 Pro" },
  ],
  modelsFetcher: { url: "https://api.orcarouter.ai/v1/models", type: "orcarouter-free" },
  passthroughModels: true,
};
